routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'auth'], function() {
    Route::get('/', function () {

        return view('layouts.pages.home.index',
         [
             'loanTypes' => \App\Models\LoanType::latest()->get(),
             'courses' => \App\Models\Course::latest()->get()
         ]);
    });
    //clients
    Route::resource('clients', 'ClientController');
    Route::put('clients-update-status/{code}', 'ClientController@updateStatus')->name('clients.update-status');
    //loans-types
    Route::resource('loan-types', 'LoanTypeController');
    //loans
    Route::resource('loans', 'LoanController');
    
    Route::get('loan-statement/{code}', 'LoanController@genLoanStatement')->name('loan-statement');
    Route::put('loans-status/{code}', 'LoanController@updateStatus')->name('loans.status');
    Route::resource('loan-repayments', 'LoanRepaymentController');
    Route::get('loan-receipt/{code}', 'LoanRepaymentController@paymentReceipt')->name('loan-receipt');
    Route::group(['prefix' => 'academy'], function() {
        
        Route::get('/', function() {
            
            return view('layouts.pages.academy.index', ['courses' => \App\Models\Course::latest()->get()]);
        })->name('academy.index');
        Route::resource('courses', 'CourseController');
        Route::resource('students', 'StudentController');
        Route::resource('student-course', 'StudentCourseController');
        Route::get('receipt-course-payment/{code}', 'StudentCourseController@paymentReceipt')->name('receipt-course-payment');
        Route::get('student-course-payments', 'StudentCourseController@coursePayments')->name('student-course-payments.index');
        Route::post('student-course-partial', 'StudentCourseController@partialPayment')->name('student-course.partial');
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Repo\Helpers\EnumConsts;

class Student extends Model
{
    //
    protected $fillable = [
        'first_name', 'code', 'last_name', 'email_address',
         'id_number', 'phone_number', 'address', 'nok_name',
         'nok_email_address', 'nok_phone_number', 'status', 'deleted_at'
        ];
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    public function scopePending($query)
    {
        return $query->where('status', EnumConsts::STATUS_pending);
    }
    public function scopeActive($query)
    {
        return $query->where('status', EnumConsts::STATUS_active);
    }
    public function scopeRejected($query)
    {
        return $query->where('status', EnumConsts::STATUS_rejected);
    }

    public function courses()
    {
        return $this->hasMany(StudentCourse::class, 'student_id');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use App\Models\Course;
use App\Models\CoursePaymentHistory;

use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('layouts.pages.academy.students.index', 
                [ 
                    'pendingStudents' => Student::pending()->latest()->get(),
                    'activeStudents' => Student::active()->latest()->get(),
                    'rejectedStudents' => Student::rejected()->latest()->get()
                ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('layouts.pages.academy.students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = $request->all();
        $data['code'] = time() + rand(15,9446564);

        Student::create($data);
        session()->flash('flash_message', 'student added successfully');

        return redirect()->route('students.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show($code)
    {
        //
        $student = Student::with(['courses'])->where('code', $code)->firstOrFail();
        $courses = [];
        if($student->courses) {
            $courses = array_map(function($st) {

                return $st['id'];
        }, $student->courses->toArray());
        }
        
        return view('layouts.pages.academy.students.view', 
                    [
                        'profile' => $student,
                        'courses' => Course::latest()->get(),
                        'coursePaymentHistory' => CoursePaymentHistory::with('studentCourse.course')->whereIn('student_course_id', $courses)->latest()->get()
                    ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        //
    }
}

resources/views/layouts/pages/academy/students/create.blade.php
@extends('layouts.app')

@section('body')
<section id="content">
        
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper" class=" grey lighten-3">
      <div class="container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h5 class="breadcrumbs-title">Students</h5>
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
            <li><a href="{{ route('students.index') }}">Students</a></li>
                <li class="active">Add student</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->
<div class="container">
    <div class="card-panel">
        <div class="card-title">
            <h5 class="left-align">Add student</h5>
        </div>
        <div class="s8 offset-s2">
            <div class="row">
                <form class="col s12" method="post" action="{{ route('students.store') }}">
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="input-field col s4">
                            <input id="first_name" name="first_name" type="text" required value="{{ old('last_name') }}">
                            <label for="first_name">First Name</label>
                            <span class="helper-text" data-error="wrong">
                                    {{ $errors->has('first_name') ? $errors->first('first_name') : ''}}
                            </span>
                        </div>
                        <div class="input-field col s4">
                            <input id="last_name" name="last_name" type="text" required value="{{ old('last_name') }}">
                            <label for="last_name">Last Name</label>
                            <span class="helper-text" data-error="wrong">
                                    {{ $errors->has('last_name') ? $errors->first('last_name') : ''}}
                            </span>
                        </div>
                        <div class="input-field col s4">
                            <input id="middle_name" name="middle_name" type="text" value="{{ old('middle_name') }}">
                            <label for="middle_name">Middle Name</label>
                            <span class="helper-text" data-error="wrong">
                                    {{ $errors->has('middle_name') ? $errors->first('middle_name') : ''}}
                            </span>
                        </div>
                     </div>
                     <div class="row">
                            <div class="input-field col s4">
                                <input id="id_number" name="id_number" type="number" required value="{{ old('id_number') }}">
                                <label for="id_number">ID Number</label>
                                <span class="helper-text" data-error="wrong">
                                        {{ $errors->has('id_number') ? $errors->first('id_number') : ''}}
                                </span>
                            </div>
                            <div class="input-field col s4">
                                <input id="email" name="email_address" type="text" required value="{{ old('email_address') }}">
                                <label for="email_address">Email</label>
                                <span class="helper-text" data-error="wrong">
                                        {{ $errors->has('email_address') ? $errors->first('email_address') : ''}}
                                </span>
                            </div>
                            <div class="input-field col s4">
                                <input id="phone_number" name="phone_number" type="number" value="{{ old('phone_number') }}" required>
                                <label for="phone_number">Phone Number</label>
                                <span class="helper-text" data-error="wrong">
                                        {{ $errors->has('phone_number') ? $errors->first('phone_number') : ''}}
                                </span>
                            </div>
                     </div>
                    <div class="row">
                        <div class="input-field col s6">
                            <input id="address" name="address" type="text" value="{{ old('address') }}">
                            <label for="address">Address</label>
                            <span class="helper-text" data-error="wrong">
                                    {{ $errors->has('address') ? $errors->first('address') : ''}}
                            </span>
                        </div>
                        <div class="input-field col s6">
                            <input id="nok_name" name="nok_name" type="text" value="{{ old('nok_name') }}">
                            <label for="nok_name">Next of kin name</label>
                            <span class="helper-text" data-error="wrong">
                                    {{ $errors->has('nok_name') ? $errors->first('nok_name') : ''}}
                            </span>
                        </div>
                    </div>
                    <div class="row">
                            <div class="input-field col s6">
                                    <input id="nok_phone_number" name="nok_phone_number" type="number" value="{{ old('nok_phone_number') }}">
                                    <label for="nok_phone_number">NOK Phone Number</label>
                                    <span class="helper-text" data-error="wrong">
                                            {{ $errors->has('nok_phone_number') ? $errors->first('nok_phone_number') : ''}}
                                    </span>
                                </div>
                            <div class="input-field col s6">
                            <input id="nok_email_address" name="nok_email_address" type="email" value="{{ old('nok_email_address') }}">
                                <label for="nok_email_address">NOK Email Address</label>
                                <span class="helper-text" data-error="wrong">
                                    {{ $errors->has('nok_email_address') ? $errors->first('nok_email_address') : ''}}
                                </span>
                            </div>
                    </div>
                      <div class="row">
                            <div class="input-field col s12">
                               <button class="btn green waves-effect waves-light right" type="submit">Save
                                    <i class="mdi-action-done-all left"></i>
                                </button>
                            </div>
                     </div>
                </form>
            </div>
        </div>
    </div>
</div>
</section>
@endsection

resources/views/layouts/pages/academy/students/index.blade.php
@extends('layouts.app')

@section('body')
<section id="content">
        
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper" class=" grey lighten-3">
      <div class="container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h5 class="breadcrumbs-title">Students</h5>
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li><a href="{{ route('academy.index') }}">Academy</a></li>
                <li class="active">List of students</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->
<div class="container">
    <div class="card-panel">
        <div class="card-title">
        <a href="{{ route('students.create') }}" class="waves-effect waves-light btn-small green  btn right"><i class="mdi-content-add left"></i>Student</a>
        </div><br><br>
        <!-- profile-page-wall -->
 <div id="profile-page-wall" class="col s12 m12 l12">
    <!-- profile-page-wall-share -->
    <div class="row">
        <!-- UpdateStatus-->
        <div id="UpdateStatus" class=" col s12  grey lighten-4">
            <div class="card-panel">
                <table class="data-table responsive-table">
                  <thead>
                      <tr>
                          <th class="center-align">No.</th>
                          <th class="center-align">Name</th>
                          <th class="center-align">Email address</th>
                          <th class="center-align">Phone number</th>
                          <th class="center-align">Id number</th>
                          <th class="center-align">Action</th>
                      </tr>
                  </thead>
               
                  <tfoot>
                      <tr>
                          <th class="center-align">No.</th>
                          <th class="center-align">Name</th>
                          <th class="center-align">Email address</th>
                          <th class="center-align">Phone number</th>
                          <th class="center-align">Id number</th>
                          <th class="center-align">Action</th>
                      </tr>
                  </tfoot>
               
                  <tbody>
                    @foreach($pendingStudents as $key => $student)
                      <tr>
                      <td class="center-align">{{ $key+1 }}</td>
                      <td class="center-align">{{ ucwords($student->first_name .' '.$student->last_name ) }}</td>
                      <td class="center-align">{{ $student->email_address }}</td>
                      <td class="center-align">{{ $student->phone_number }}</td>
                        <td class="center-align">{{ $student->id_number }}</td>
                        <td class="center-align">
                            <a href="{{ route('students.show', $student->code) }}" title="view student details" class="btn-floating waves-effect waves-light btn-small green">
                                <i class="mdi-action-visibility"></i>
                              </a>
                        </td>
                      </tr>
                    @endforeach
                  </tbody>
                </table>
          </div>
        </div>
      </div>
    </div>
    <!--/ profile-page-wall-share -->
  </div>
  <!--/ profile-page-wall -->
</div>
</section>
@endsection
@section('css')
    <!-- Custome CSS-->    
    <link href="/assets/css/custom-style.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="/assets/js/plugins/perfect-scrollbar/perfect-scrollbar.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="/assets/js/plugins/data-tables/css/jquery.dataTables.min.css" type="text/css" rel="stylesheet" media="screen,projection">
@endsection
@section('js')
<script type="text/javascript" src="/assets/js/plugins/data-tables/js/jquery.dataTables.min.js"></script>
<script>
    $(function(){
        $('.data-table').DataTable();
    })
</script>
@endsection