routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'auth'], function() {
    Route::get('/', function () {

        return view('layouts.pages.home.index',
         [
             'loanTypes' => \App\Models\LoanType::latest()->get(),
             'courses' => \App\Models\Course::latest()->get()
         ]);
    });
    //clients
    Route::resource('clients', 'ClientController');
    Route::put('clients-update-status/{code}', 'ClientController@updateStatus')->name('clients.update-status');
    //loans-types
    Route::resource('loan-types', 'LoanTypeController');
    //loans
    Route::resource('loans', 'LoanController');
    
    Route::get('loan-statement/{code}', 'LoanController@genLoanStatement')->name('loan-statement');
    Route::put('loans-status/{code}', 'LoanController@updateStatus')->name('loans.status');
    Route::resource('loan-repayments', 'LoanRepaymentController');
    Route::get('loan-receipt/{code}', 'LoanRepaymentController@paymentReceipt')->name('loan-receipt');
    Route::group(['prefix' => 'academy'], function() {
        
        Route::get('/', function() {
            
            return view('layouts.pages.academy.index', ['courses' => \App\Models\Course::latest()->get()]);
        })->name('academy.index');
        Route::resource('courses', 'CourseController');
        Route::resource('students', 'StudentController');
        Route::resource('student-course', 'StudentCourseController');
        Route::get('receipt-course-payment/{code}', 'StudentCourseController@paymentReceipt')->name('receipt-course-payment');
        Route::get('student-course-payments', 'StudentCourseController@coursePayments')->name('student-course-payments.index');
        Route::post('student-course-partial', 'StudentCourseController@partialPayment')->name('student-course.partial');
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Loan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Repo\Helpers\EnumConsts;

class Loan extends Model
{
    //
    protected $fillable = [
        'client_id', 'loan_type_id', 'code', 'loan_interest', 
        'amount_disbursed', 'date_of_disbursement',
         'loan_period', 'period_type', 'loan_level',
         'installment_amount', 'installment_type', 'remaining_payment',
         'status', 'deleted_at'
        ];
    
    protected $dates = ['created_at', 'date_of_disbursement', 'end_of_loan_term', 'deleted_at', 'updated_at'];
/**
 * client relationship
 */
    public function client()
    {
        return $this->belongsTo(Client::class);
    }
    /**
     * loan types
     */
    public function loanType()
    {
        return $this->belongsTo(LoanType::class);
    }
    public function repayments()
    {
        return $this->hasMany(LoanRepayment::class, 'loan_id');
    }
    /**
     * query scopes going down
     */
    public function scopePending($query)
    {
        return $query->where('status', EnumConsts::STATUS_pending);
    }
    public function scopeActive($query)
    {
        return $query->where('status', EnumConsts::STATUS_active);
    }
    public function scopeRejected($query)
    {
        return $query->where('status', EnumConsts::STATUS_rejected);
    }
}

app/Models/LoanType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class LoanType extends Model
{
    //
    protected $fillable = ['name', 'code', 'interest', 'description', 'deleted_at'];

    protected $dates = ['created_at', 'updated_at'];
}

app/Http/Controllers/LoanController.php
<?php

namespace App\Http\Controllers;

use App\Models\LoanType;
use App\Models\Loan;
use App\Models\Client;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Repo\Helpers\EnumConsts;
use PDF;

class LoanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('layouts.pages.loans.index', 
            [
                'activeLoans' => Loan::with(['loanType', 'client'])->active()->latest()->get(),
                'pendingLoans' => Loan::with(['loanType', 'client'])->pending()->get(),
                'rejectedLoans' => Loan::with(['loanType', 'client'])->rejected()->latest()->get()
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $loanTypes = LoanType::latest()->get();
        if(request()->ajax()) {
            
            // return response()->json($loanTypes);
        }

        return view('layouts.pages.loans.create', [ 'loanTypes' => $loanTypes, 'clients' => Client::latest()->active()->get()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = $request->all();
        $data['code'] = uniqid();
        $data['date_of_disbursement'] = Carbon::parse($request->get('date_of_disbursement'));
        $data['end_of_loan_term'] = Carbon::parse($request->get('end_of_loan_term'));
        Loan::create($data);
        session()->flash('flash_message', 'Loan disbursed successfully.');

        return redirect()->route('loans.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function show($code)
    {
        //
        return view('layouts.pages.loans.view', ['loan' => Loan::with(['client', 'loanType', 'repayments'])->where('code', $code)->first()]);
    }
    /**
     * loan update status
     */
    public function updateStatus(Request $request, $code)
    {
        $loan = Loan::where('code', $code)->firstOrFail();
        /**
         * @todo generate loan statement
         * generate loan statement
         */
        if($request->get('status') == EnumConsts::STATUS_active) {

        }
        /**
         * @todo mail notification/SMS
         */
        $loan->update($request->all());
        session()->flash('flash_message', 'Loan updated successfully');

        return redirect()->route('loans.index');
    }
    public function genLoanStatement($code)
    {
        
        $loan = Loan::with(['client', 'loanType'])->where('code', $code)->firstOrFail();

        $pdf = PDF::loadView('layouts.docs.loans.loan-statement', ['loan' => $loan ]);

        return $pdf->download(time().'_loan_statement.pdf');
    }
}

resources/views/layouts/pages/loans/create.blade.php
@extends('layouts.app')
@section('css')
<style>
    .light-green {
        background-color : #ff9900 !important;
    }
</style>
@endsection
@section('body')
<section id="content">
        
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper" class=" grey lighten-3">
      <div class="container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h5 class="breadcrumbs-title">Loan application</h5>
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li><a href="{{ route('loans.index') }}">Loan applications</a></li>
                <li class="active">Loan application</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->
<div class="row">
    <div class="col s12">
    <div class="card-panel">
        <div class="card-title">
            <h5 class="left-align">Loan application</h5>
        </div>
            <div class="row">
                <form class="col s12" method="post" action="{{ route('loans.store') }}">
                    @csrf
                    <div class="row">
                        <div class="input-field col s4">
                            <select name="client_id" id="client_id">
                                <option disabled selected placeholder>Select client...</option>
                                @foreach($clients as $client)
                                    <option value="{{ $client->id }}">{{ $client->first_name .' '.$client->last_name }}</option>
                                @endforeach
                            </select>
                            <label for="client_id">Client</label>
                            <span class="helper-text" data-error="wrong">
                                    {{ $errors->has('client_id') ? $errors->first('client_id') : ''}}
                            </span>
                        </div>
                        <div class="input-field col s4">
                            <select name="loan_type_id" id="loan_type_id">
                                    <option disabled selected placeholder>Select loan type...</option>
                                @foreach($loanTypes as $loanType)
                                    <option value="{{ $loanType->id }}">{{ $loanType->name }}</option>
                                @endforeach
                            </select>
                            <label for="loan_type_id">Loan type</label>
                        </div>
                        <div class="input-field col s4">
                            <input id="amount_disbursed" name="amount_disbursed" type="number" required>
                            <label for="amount_disbursed">Loan Amount (KES)</label>
                            <span class="helper-text" data-error="wrong"></span>
                        </div>
                        <div class="input-field col s4">
                                <input id="loan_period" name="loan_period" type="number" required>
                                <label for="loan_period">Loan period</label>
                                <span class="helper-text" data-error="wrong"></span>
                        </div>
                        <div class="input-field col s4">
                            <select name="period_type" id="period_type" placeholder='select period type...' required>
                                    <option value="{{ \Repo\Helpers\EnumConsts::LOAN_PERIOD_month }}">Months(s)</option>
                                    <option value="{{ \Repo\Helpers\EnumConsts::LOAN_PERIOD_week }}">Weeks(s)</option>
                             </select>
                            <label for="installment_type">Period Type</label>
                            <span class="helper-text" data-error="wrong"></span>
                        </div>
                        <div class="input-field col s4">
                            <select name="installment_type" id="installment_type" placeholder='select installmant type...' required>
                                <option value="{{ \Repo\Helpers\EnumConsts::INSTALLMENT_TYPE_WEEKLY }}">Month</option>
                                <option value="{{ \Repo\Helpers\EnumConsts::INSTALLMENT_TYPE_MONTHLY }}">Week</option>
                            </select>
                            <label for="installment_type">Installment type</label>
                            <span class="helper-text" data-error="wrong"></span>
                        </div>
                        <div class="input-field col s4">
                            <input id="installment_amount" name="installment_amount" type="number" step="2" required value="">
                            <label for="installment_amount">Installment Amount</label>
                            <span class="helper-text" data-error="wrong"></span>
                        </div>
                        <div class="input-field col s4">
                            <select name="loan_level" id="loan_level" placeholder='select loan level...' required>
                                <option value="{{ \Repo\Helpers\EnumConsts::LEVEL_one }}">Level one</option>
                                <option value="{{ \Repo\Helpers\EnumConsts::LEVEL_two }}">Level two</option>
                                <option value="{{ \Repo\Helpers\EnumConsts::LEVEL_three }}">Level three</option>
                                <option value="{{ \Repo\Helpers\EnumConsts::LEVEL_four }}">Level four</option>
                                <option value="{{ \Repo\Helpers\EnumConsts::LEVEL_five }}">Level five</option>
                                <option value="{{ \Repo\Helpers\EnumConsts::LEVEL_six }}">Level six</option>
                            </select>
                            <label for="loan_level">Loan Level</label>
                            <span class="helper-text" data-error="wrong">
                                {{ $errors->has('loan_level') ? $errors->first('loan_level') : ''}}
                            </span>
                        </div>
                     </div>
                      <div class="row">
                            <div class="input-field col s12">
                               <button class="btn green waves-effect waves-light right" type="submit">Save <i class="mdi-action-done-all left"></i></button>
                            </div>
                     </div>
                </form>
            </div>
        </div>
    </div>
</div>
</section>
@endsection
@section('css')
<link rel="stylesheet" href="/css/app.css">
<link rel="stylesheet" href="/assets/js/plugins/select2/select2-materialize.css">
@endsection
@section('js')
<script src="/js/app.js"></script>
<script src="/js/loanCalculator.js"></script>
@endsection