routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'auth'], function() {
    Route::get('/', function () {

        return view('layouts.pages.home.index',
         [
             'loanTypes' => \App\Models\LoanType::latest()->get(),
             'courses' => \App\Models\Course::latest()->get()
         ]);
    });
    //clients
    Route::resource('clients', 'ClientController');
    Route::put('clients-update-status/{code}', 'ClientController@updateStatus')->name('clients.update-status');
    //loans-types
    Route::resource('loan-types', 'LoanTypeController');
    //loans
    Route::resource('loans', 'LoanController');
    
    Route::get('loan-statement/{code}', 'LoanController@genLoanStatement')->name('loan-statement');
    Route::put('loans-status/{code}', 'LoanController@updateStatus')->name('loans.status');
    Route::resource('loan-repayments', 'LoanRepaymentController');
    Route::get('loan-receipt/{code}', 'LoanRepaymentController@paymentReceipt')->name('loan-receipt');
    Route::group(['prefix' => 'academy'], function() {
        
        Route::get('/', function() {
            
            return view('layouts.pages.academy.index', ['courses' => \App\Models\Course::latest()->get()]);
        })->name('academy.index');
        Route::resource('courses', 'CourseController');
        Route::resource('students', 'StudentController');
        Route::resource('student-course', 'StudentCourseController');
        Route::get('receipt-course-payment/{code}', 'StudentCourseController@paymentReceipt')->name('receipt-course-payment');
        Route::get('student-course-payments', 'StudentCourseController@coursePayments')->name('student-course-payments.index');
        Route::post('student-course-partial', 'StudentCourseController@partialPayment')->name('student-course.partial');
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/LoanTypeController.php
<?php

namespace App\Http\Controllers;

use App\Models\LoanType;
use Illuminate\Http\Request;

class LoanTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('layouts.pages.loan-types.index', ['loanTypes' => LoanType::latest()->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = $request->all();
        $data['code'] = uniqid();
        LoanType::create($data);
        session()->flash('flash_message', 'loan type added successfully');

        return redirect()->route('loan-types.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\LoanType  $loanType
     * @return \Illuminate\Http\Response
     */
    public function show(LoanType $loanType)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\LoanType  $loanType
     * @return \Illuminate\Http\Response
     */
    public function edit(LoanType $loanType)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\LoanType  $loanType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, LoanType $loanType)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\LoanType  $loanType
     * @return \Illuminate\Http\Response
     */
    public function destroy(LoanType $loanType)
    {
        //
    }
}

resources/views/layouts/pages/loan-types/index.blade.php
@extends('layouts.app')

@section('body')
<section id="content">
        
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper" class=" grey lighten-3">
      <div class="container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h5 class="breadcrumbs-title">Loan Types</h5>
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">List of Loan Types</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->
    <div class="row">
        <div class="col s12 m6 l6">
            <div class="card-panel">
            <form class="" action="{{ route('loan-types.store')}}" method="POST">
                        @csrf
                            <div class="row">
                              <div class="input-field col s6">
                                <input id="name" name="name" type="text" required>
                                <label for="name">Name</label>
                              </div>
                                <div class="input-field col s6">
                                  <input id="interest" name="interest" type="number" required>
                                  <label for="interest">Interest %(per month)</label>
                                </div>
                            </div>
                            <div class="row">
                              <div class="input-field col s12">
                                <textarea id="description" name="description" class="materialize-textarea"></textarea>
                                <label for="description">Description</label>
                              </div>
                              <div class="row">
                                <div class="input-field col s12">
                                  <button class="btn green waves-effect waves-light right" type="submit" name="action">Save
                                    <i class="mdi-action-done-all right"></i>
                                  </button>
                                </div>
                              </div>
                            </div>
                    </form>
            </div>
        </div>
        <div class="col s12 m6 l6">
            <div class="card-panel">
                    <h4 class="header">Loan Types List</h4>
                  <ul id="projects-collection" class="collection">
                    <li class="collection-item avatar">
                      <i class="mdi-file-folder circle light-blue"></i>
                      <span class="collection-header">Loans</span>
                      <a href="#" class="secondary-content"><i class="mdi-action-shopping-basket"></i></a>
                    </li>
                    @foreach($loanTypes as $key => $loanType)
                    <li class="collection-item">
                      <div class="row">
                        <div class="col s4">
                        <p class="collections-title">{{ $loanType->name }}</p>
                        <p class="collections-title">Interest <b>{{ $loanType->interest }}%</b></p>
                        </div>
                        <div class="col s8">
                            <p class="collections-content">
                                {{ $loanType->description }}
                              </p>
                              <a href="{{ route('loan-types.show', $loanType->code) }}" title="view loans available" class="btn-floating waves-effect waves-light btn-small blue">
                                  <i class="mdi-action-visibility"></i>
                              </a>
                        </div>
                      </div>
                    </li>
                    @endforeach
                  </ul>
            </div>
        </div>
</section>
@endsection